[package]
name = "tradebot-execution"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
tradebot-common = { path = "../common" }
tradebot-core = { path = "../core" }
tradebot-data = { path = "../data" }
tradebot-storage = { path = "../storage" }
tradebot-wallet = { path = "../wallet" }
async-trait = "0.1"
chrono = { workspace = true }
rust_decimal = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
base64 = "0.22"
solana-message = { version = "4.2.4", features = ["wincode"] }
solana-signature = { version = "3.4.1", features = ["wincode"] }
solana-transaction = { version = "4.1.5", features = ["wincode"] }
wincode = "0.5"

[dev-dependencies]
serde_json = { workspace = true }
tempfile = "3"
wiremock = "0.6"
solana-keypair = "3.1.2"
solana-address = "2.6.1"
solana-instruction = "3.4.0"
solana-hash = "4.4.0"
solana-signer = "3.0.1"
ed25519-dalek = { version = "2", features = ["rand_core"] }
bs58 = "0.5"
